steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ['--version']
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ['test']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-east1-docker.pkg.dev/${PROJECT_ID}/gmshamca/spring-build--trigger/${_IMAGE}', '.'] 
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/still-confution", "--build-arg=JAR_FILE=target/${_IMAGE}", "."]
images: ["gcr.io/$PROJECT_ID/still-confution"]
