steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ['--version']
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ['test']
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}', '.' ]



    
    
  
