steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ['--version']
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ['test']
    entrypoint: mvn
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/New-CR-Image", "--build-arg=JAR_FILE=target/${_IMAGE}", "."]
images: ["gcr.io/$PROJECT_ID/New-CR-Image"]
