steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ['--version']
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ['test']
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'asis-east1-docker.pkg.dev/sapient-poet-351315/spring-build--trigger/myproject-0.0.1-SNAPSHOT.jar', '.' ]
images: ['asis-east1-docker.pkg.dev/sapient-poet-351315/spring-build--trigger/myproject-0.0.1-SNAPSHOT.jar'] 
